from .employees.employee_list import employee_list
from .employees.employee_form import employee_form
from .home import home
from .auth.logout import logout_user
from .computers.list import computer_list
from .computers.form import computer_form
from .computers.details import computer_details
from .computers.delete import computer_delete
from .training_programs.training_list import training_list
from .training_programs.training_form import training_form
from .departments.department_list import department_list
from .departments.department_form import department_form
